### ISSUE TITLE
Panic on Invalid Input in `html_forge::parser::Parser::parse`

### ISSUE THREAD

**Issue by rfuzz** [benodiwal/html_forge#1]
Hi there,

While performing fuzz testing on `html_forge::parser::Parser`, I encountered an input that triggers a panic:

```rust
use html_forge::parser::Parser;

fn main() {
    let input = String::from("<!-%");
    let mut parser = Parser::new(input);
    
    match parser.parse() {
        Ok(node) => println!("Parsed Node: {:?}", node),
        Err(err) => eprintln!("Parsing error: {:?}", err),
    }
}
```

It seems that the exception for invalid input isn’t being handled properly and is instead causing the program to panic directly. When running the program with `cargo run`, it results in a panic:

```shell
thread 'main' panicked at /home/ubuntu/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/html_forge-0.1.0/src/parser/mod.rs:112:13:
Invalid attribute value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here’s the version information I’m using:

```toml
[dependencies]
html_forge = "0.1.0"
```

**Comment by benodiwal** [comment]
looking into it, thanks for pointing out !!

**Comment by rfuzz** [comment]
Uh, I just ran a test, and parsing `<!` also triggers a panic.

```shell
thread 'main' panicked at /home/ubuntu/html_forge/src/parser/mod.rs:147:41:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
